title: "Robophysics Workshop"
description: "Hands-on locomotion, mechanics, and robophysical experiment design"

# Use remote_theme instead of theme:
remote_theme: just-the-docs/just-the-docs

url: "https://crablabjames.github.io"
baseurl: "/robophysics-workshop"

nav_enabled: true
search_enabled: true

plugins:
  - jekyll-remote-theme

aux_links:
  "Crab Lab @ Georgia Tech":
    - "https://crablab.gatech.edu/"
aux_links_new_tab: true
